name: CI

# Events that trigger workflow
on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  build_wheels:
    name: Build Wheels (${{matrix.os.name}})
    runs-on: ${{ matrix.os.runner }}
    strategy:
      matrix:
        os:
          [
            {
              name: "macOS 13",
              family: "macos",
              runner: "macos-13",
              archs: "x86_64",
            },
            {
              name: "macOS 14",
              family: "macos",
              runner: "macos-14",
              archs: "arm64",
            },
          ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions/setup-python@v3
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.20.0
        env:
          CIBW_SKIP: pp*
          CIBW_ARCHS: ${{ matrix.os.archs }}
          CIBW_BUILD_VERBOSITY: "1"
          CIBW_ENVIRONMENT_MACOS: >
            MACOSX_DEPLOYMENT_TARGET=11
          CIBW_BEFORE_BUILD: |
            python3 --version
            python3-config --includes
          CIBW_TEST_COMMAND: python3 -c "import example; example.python_hello_world()"
